name: Ruby

on: push

jobs:
  version-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.ref != 'refs/heads/master'
        with:
          ref: master
      - uses: actions/checkout@v4

      - name: Version change required on master
        if: github.ref == 'refs/heads/master'
        run: 'if git diff --exit-code HEAD^ -- lib/app_configurable/version.rb ; then exit 1 ; else exit 0 ; fi'

      - name: Changelog change required on master
        if: github.ref == 'refs/heads/master'
        run: 'if git diff --exit-code HEAD^ -- CHANGELOG.md ; then exit 1 ; else exit 0 ; fi'

      - name: Version change required on branch
        if: github.ref != 'refs/heads/master'
        run: 'if git diff --exit-code origin/master -- lib/app_configurable/version.rb ; then exit 1 ; else exit 0 ; fi'

      - name: Changelog change required on branch
        if: github.ref != 'refs/heads/master'
        run: 'if git diff --exit-code origin/master -- CHANGELOG.md ; then exit 1 ; else exit 0 ; fi'

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1
          bundler-cache: true

      - name: Lint
        run: bundle exec rubocop

  test:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1'
          - '3.2'
          - '3.3'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rspec


  publish:
    needs: [test, lint, version-changed]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.1
      - uses: rubygems/release-gem@v1