#!/usr/bin/ruby

#
# This script generates prerelase version strings in CI
# This way you get versions like 1.2.3.pre.commitsha
#

VERSION_PATH = '../../lib/app_configurable/version.rb'
DEFAULT_BRANCH = 'master'

Dir.chdir(__dir__)

branch = `git branch --show-current`.chomp
return if branch == DEFAULT_BRANCH

unless ENV['GIT_SHA']
  warn 'WARNING: GIT_SHA is not set'
  exit(-1)
end

# Get version from source
require VERSION_PATH
base_version = AppConfigurable::VERSION
short_sha = ENV['GIT_SHA'][0..6]

prerelease_suffix = ".pre.#{short_sha}"

version_string = <<-RUBY
# AUTO-GENERATED BY CI
module AppConfigurable
  VERSION = '#{base_version}#{prerelease_suffix}'
end
RUBY

File.write(VERSION_PATH, version_string)